### ISSUE TITLE
Facebook\FacebookClient::__construct() must be an instance of Facebook\HttpClients\FacebookHttpClientInterface

### ISSUE THREAD

**Issue by tomekit** [facebook/php-graph-sdk#862]
Hi,

I've installed the PHP SDK and trying to run it using example from the top README.

```
$fb = new \Facebook\Facebook([
    'app_id' => '<id>',
    'app_secret' => '<secret>',
    'default_graph_version' => 'v2.10'
]);
```

I get the:
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Facebook\FacebookClient::__construct() must be an instance of Facebook\HttpClients\FacebookHttpClientInterface, instance of Facebook\HttpClients\FacebookCurlHttpClient given, called in /data/event/vendor/facebook/graph-sdk/src/Facebook/Facebook.php on line 148 and defined in /data/event/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php:94
Stack trace:
#0 /data/event/vendor/facebook/graph-sdk/src/Facebook/Facebook.php(148): Facebook\FacebookClient->__construct(Object(Facebook\HttpClients\FacebookCurlHttpClient), false)
#1 /data/event/htdocs/gallery.php(6): Facebook\Facebook->__construct(Array)
#2 {main}
  thrown in /data/event/vendor/facebook/graph-sdk/src/Facebook/FacebookClient.php on line 94
```

What's the problem?

I run the `PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )`

**Comment by bobitza** [comment]
require 'facebook/autoload.php'; Try to use this

**Comment by yguedidi** [comment]
is this solved? it looks like an error due to autoloading

**Comment by tomekit** [comment]
Since the app I was working on used: `"facebook/php-sdk-v4" : "4.0.*"` previously, I've given up on this SDK, as was pushed by time and used that particular version, which worked fine.
Let's close this, it's no longer an issue for me. 
Thanks for your help anyway !

**Comment by jdanarola** [comment]
I am facing same issue.  
I also tried require 'facebook/autoload.php'; still not working.
please provide solution to it.
